spring:
  profiles:
    include:
    - mysql
    - feign
    - mongo

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com:
      example:
        springbootdemos:
          rest:
            feignclient: DEBUG
    org:
      springframework:
        security: DEBUG

