spring:
  profiles:
    include:
    - mysql
    - feign
    - mongo

logging:
  level:
    com:
      example:
        springbootdemos:
          rest:
            feignclient: DEBUG
    org:
      springframework:
        security: DEBUG

