spring:
  jpa:
    database:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/aplicacionmdi?serverTimezone=UTC
    username: root
    password: root
