spring:
  profiles:
    include:
    - mysql
    - feign
    - mongo
    active: vector

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com:
      example:
        springbootdemos:
          rest:
            feignclient: DEBUG
    org:
      springframework:
        security: error


management.endpoint.beans.enabled: true
management.endpoint.info.enabled: true
management.endpoint.metrics.enabled: true
management.endpoint.mappings.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, metrics, mappings, health, beans
  endpoint:
    health:
      show-details: always

